# TIMEOUTS
MODULE_TIMEOUT = 60
BATTERY_CELL_TIMEOUT = 3

# SETPOINTS
BATTERY_CELL_VOLTAGE_HIGH_WARNING_SETPOINT = 4.1
BATTERY_CELL_VOLTAGE_HIGH_ALARM_SETPOINT = 4.25
BATTERY_CELL_VOLTAGE_HIGH_FAULT_SETPOINT = 4.4
BATTERY_CELL_VOLTAGE_LOW_WARNING_SETPOINT = 3.55
BATTERY_CELL_VOLTAGE_LOW_ALARM_SETPOINT = 3.5
BATTERY_CELL_VOLTAGE_LOW_FAULT_SETPOINT = 3.25

BATTERY_CELL_TEMP_HIGH_WARNING_SETPOINT = 35
BATTERY_CELL_TEMP_HIGH_ALARM_SETPOINT = 45
BATTERY_CELL_TEMP_HIGH_FAULT_SETPOINT = 55
BATTERY_CELL_TEMP_LOW_WARNING_SETPOINT = 15
BATTERY_CELL_TEMP_LOW_ALARM_SETPOINT = 10
BATTERY_CELL_TEMP_LOW_FAULT_SETPOINT = 5

# Alarms
BATTERY_CELL_TEMP_HIGH_ALARM = 21
BATTERY_CELL_TEMP_LOW_ALARM = 22
BATTERY_CELL_VOLTAGE_HIGH_ALARM = 23
BATTERY_CELL_VOLTAGE_LOW_ALARM = 24


# Faults - There are too many potential faults to fit in a bitwise fashion, assuming in most cases they won't occur simultaneously
CONTROL_HEARTBEAT_TIMEOUT_FAULT = 10
CONTROL_HEARTBEAT_ECHO_TIMEOUT_FAULT = 11
CONTROL_POWER_COMMAND_FAULT = 12
CONTROL_CURRENT_COMMAND_FAULT = 13
CONTROL_ESTOP_FAULT = 14
CONTROL_DOOR_OPEN_FAULT = 15

BATTERY_HEARTBEAT_TIMEOUT_FAULT = 20
BATTERY_CELL_TEMP_HIGH_FAULT = 21
BATTERY_CELL_TEMP_LOW_FAULT = 22
BATTERY_CELL_VOLTAGE_HIGH_FAULT = 23
BATTERY_CELL_VOLTAGE_LOW_FAULT = 24

INVERTER_HEARTBEAT_TIMEOUT_FAULT = 30

AC_METER_HEARTBEAT_TIMEOUT_FAULT = 40

DC_METER_HEARTBEAT_TIMEOUT_FAULT = 50

DIO_HEARTBEAT_TIMEOUT_FAULT = 60

AIO_HEARTBEAT_TIMEOUT_FAULT = 70

MIO_HEARTBEAT_TIMEOUT_FAULT = 80

SWITCH_HEARTBEAT_TIMEOUT_FAULT = 90

LI_ION_HEARTBEAT_TIMEOUT_FAULT = 100

DCDC_HEARTBEAT_TIMEOUT_FAULT = 110

AIRCON_HEARTBEAT_TIMEOUT_FAULT = 120

SENSOR_HEARTBEAT_TIMEOUT_FAULT = 130

FUEL_CELL_HEARTBEAT_TIMEOUT_FAULT = 140

AC_GEN_HEARTBEAT_TIMEOUT_FAULT = 150

AC_WIND_HEARTBEAT_TIMEOUT_FAULT = 160

AC_SOLAR_HEARTBEAT_TIMEOUT_FAULT = 170

DC_SOLAR_HEARTBEAT_TIMEOUT_FAULT = 180

AC_EFM_HEARTBEAT_TIMEOUT_FAULT = 190

DC_EFM_HEARTBEAT_TIMEOUT_FAULT = 200

EV_CHARGER_HEARTBEAT_TIMEOUT_FAULT = 210

SCADA_HEARTBEAT_TIMEOUT_FAULT = 220

LOGGING_HEARTBEAT_TIMEOUT_FAULT = 230

CLIENT_HEARTBEAT_TIMEOUT_FAULT = 240

UNDEFINED_HEARTBEAT_TIMEOUT_FAULT = 250